import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
   subsets: ["latin"],
   variable: "--font-inter",
   display: "swap",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <Toaster richColors closeButton />
         <body
            className={`${inter.variable} flex justify-center bg-slate-900 text-white`}
         >
            {children}
         </body>
      </html>
   );
}
